# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 791c7664ab2d8bab04583ee1a44ba3cb3aab24518878c86679b64b6f9406e0b6cca185e3a9e198f2519253386d2384154ca58d435628f775f860dab534778a59

test:
  secret_key_base: cd167befd54815163e3003c635eb01938263352ca9789cfe40c6e33d20c35498857b3729dbf8febd80f8e9775dd9567852080751cf6a1e562ff88c154455716c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
